import type { DatasetMetadata } from "../dataset/datasetTypes";
import type { AnalyticsTask } from "../tasks";
import { getWorkbookMetadata } from "../workbook";
import { buildWorkbookRelationshipRegistry } from "../workbookRelationships";
import type {
  RelationshipAwareTaskPlan,
  RelationshipJoinRequirementStatus,
} from "./relationshipAwarePlanningTypes";

const confidenceRank = {
  low: 1,
  medium: 2,
  high: 3,
} as const;

const tasksThatMayNeedRelationships = new Set([
  "task_best_performing_products",
  "task_customer_inactivity_detection",
  "task_compare_departments",
  "task_profit_drop_investigation",
  "task_unusual_sales_behavior",
]);

const inferJoinRequirementStatus = (
  task: AnalyticsTask,
  matchingCount: number,
): RelationshipJoinRequirementStatus => {
  if (matchingCount === 0) {
    return tasksThatMayNeedRelationships.has(task.id) ? "unsupported" : "not_required";
  }
  if (tasksThatMayNeedRelationships.has(task.id)) return "may_help";
  if (task.category === "correlation_analysis" || task.category === "forecasting") return "may_help";
  return "not_required";
};

const buildReadinessNotes = (
  status: RelationshipJoinRequirementStatus,
  matchingCount: number,
) => {
  if (status === "unsupported") {
    return [
      "No workbook relationship preview currently matches this task category.",
      "Future multi-sheet planning may need confirmed worksheet relationships before execution.",
    ];
  }
  if (status === "may_help") {
    return [
      `${matchingCount} workbook relationship preview${matchingCount === 1 ? "" : "s"} may support this task later.`,
      "Future execution must validate worksheet mappings and accepted relationship contracts first.",
    ];
  }
  if (status === "likely_required") {
    return [
      "This task will likely require multi-sheet relationship support in a future phase.",
      "No join is executed or generated by this planning preview.",
    ];
  }
  return [
    "This task can remain single-sheet for now.",
    "Workbook relationships are optional planning context only.",
  ];
};

const buildMetadataAwareExplanation = (
  relatedWorksheets: string[],
  status: RelationshipJoinRequirementStatus,
) => {
  if (relatedWorksheets.length === 0) return null;
  if (status === "not_required") {
    return `This task can use the active worksheet, while ${relatedWorksheets.join(" and ")} remain optional future context.`;
  }
  return `This task may use ${relatedWorksheets.join(" and ")} worksheets in a future multi-sheet workflow if their relationship is confirmed.`;
};

export const buildRelationshipAwareTaskPlan = (
  task: AnalyticsTask,
  dataset: DatasetMetadata | null,
): RelationshipAwareTaskPlan => {
  const workbook = getWorkbookMetadata(dataset);
  if (!workbook) {
    return {
      taskId: task.id,
      hasWorkbookContext: false,
      matchingJoinPreviews: [],
      relatedWorksheets: [],
      suggestedRelationshipPaths: [],
      highestConfidence: null,
      supportedTaskCategories: [],
      futureJoinRequirementStatus: "not_required",
      readinessNotes: ["No workbook context is active for this task."],
      metadataAwareExplanation: null,
    };
  }

  const registry = buildWorkbookRelationshipRegistry(workbook);
  const matchingJoinPreviews = registry.joinPlanPreviews.filter((preview) =>
    preview.supportedTaskCategories.includes(task.category),
  );
  const relationshipIds = new Set(matchingJoinPreviews.flatMap((preview) => preview.relationshipIds));
  const matchingRelationships = registry.relationships.filter((relationship) =>
    relationshipIds.has(relationship.id),
  );
  const relatedWorksheets = Array.from(
    new Set(matchingJoinPreviews.flatMap((preview) => preview.relatedSheets)),
  );
  const highestConfidence =
    matchingRelationships
      .map((relationship) => relationship.confidenceLevel)
      .sort((left, right) => confidenceRank[right] - confidenceRank[left])[0] || null;
  const supportedTaskCategories = Array.from(
    new Set(matchingJoinPreviews.flatMap((preview) => preview.supportedTaskCategories)),
  );
  const futureJoinRequirementStatus = inferJoinRequirementStatus(task, matchingJoinPreviews.length);

  return {
    taskId: task.id,
    hasWorkbookContext: true,
    matchingJoinPreviews,
    relatedWorksheets,
    suggestedRelationshipPaths: matchingJoinPreviews.map(
      (preview) => preview.suggestedRelationshipPath,
    ),
    highestConfidence,
    supportedTaskCategories,
    futureJoinRequirementStatus,
    readinessNotes: buildReadinessNotes(futureJoinRequirementStatus, matchingJoinPreviews.length),
    metadataAwareExplanation: buildMetadataAwareExplanation(
      relatedWorksheets,
      futureJoinRequirementStatus,
    ),
  };
};
