import type { EngineAdapter } from "./engineAdapterTypes";

export const engineAdapterRegistry: EngineAdapter[] = [
  {
    id: "duckdb_sql",
    label: "DuckDB SQL Engine",
    description: "Future adapter for SQL-backed filtering, aggregation, comparison, and summaries.",
    engineType: "duckdb_sql",
    supportedTasks: [
      "sales_analysis",
      "customer_analytics",
      "financial_analysis",
      "anomaly_detection",
      "operational_intelligence",
      "workforce_analytics",
      "correlation_analysis",
    ],
    supportedExecutionSteps: [
      "prepare_metric",
      "prepare_dimension",
      "prepare_date_field",
      "aggregate",
      "compare",
      "correlate",
      "detect_anomaly",
      "summarize",
    ],
    supportedResultTypes: ["table", "summary", "diagnostic", "explanation", "chart_preview"],
    supportsWorkbookRelationships: false,
    supportsForecasting: false,
    supportsCorrelation: true,
    supportsAnomalyDetection: true,
    supportsStatisticalAnalysis: false,
    supportsVisualization: false,
    readinessLevel: "metadata_only",
  },
  {
    id: "excel_workbook",
    label: "Excel Workbook Engine",
    description: "Future adapter for worksheet-aware workflows and workbook relationship planning.",
    engineType: "excel_workbook",
    supportedTasks: [
      "sales_analysis",
      "customer_analytics",
      "financial_analysis",
      "anomaly_detection",
      "operational_intelligence",
      "workforce_analytics",
    ],
    supportedExecutionSteps: [
      "prepare_metric",
      "prepare_dimension",
      "prepare_date_field",
      "aggregate",
      "compare",
      "detect_anomaly",
      "summarize",
    ],
    supportedResultTypes: ["table", "summary", "diagnostic", "explanation", "chart_preview"],
    supportsWorkbookRelationships: true,
    supportsForecasting: false,
    supportsCorrelation: false,
    supportsAnomalyDetection: true,
    supportsStatisticalAnalysis: false,
    supportsVisualization: false,
    readinessLevel: "metadata_only",
  },
  {
    id: "python_preview",
    label: "Python Analysis Engine",
    description: "Future adapter for forecasting, statistical checks, anomaly detection, and modeling.",
    engineType: "python_analysis",
    supportedTasks: [
      "sales_analysis",
      "forecasting",
      "customer_analytics",
      "financial_analysis",
      "anomaly_detection",
      "operational_intelligence",
      "workforce_analytics",
      "correlation_analysis",
    ],
    supportedExecutionSteps: [
      "prepare_metric",
      "prepare_dimension",
      "prepare_date_field",
      "aggregate",
      "compare",
      "forecast",
      "correlate",
      "detect_anomaly",
      "summarize",
    ],
    supportedResultTypes: ["table", "summary", "diagnostic", "explanation", "chart_preview"],
    supportsWorkbookRelationships: false,
    supportsForecasting: true,
    supportsCorrelation: true,
    supportsAnomalyDetection: true,
    supportsStatisticalAnalysis: true,
    supportsVisualization: true,
    readinessLevel: "metadata_only",
  },
  {
    id: "r_preview",
    label: "R Statistical Analysis Engine",
    description: "Future adapter for statistical procedures, forecasting, and correlation workflows.",
    engineType: "r_analysis",
    supportedTasks: [
      "forecasting",
      "financial_analysis",
      "anomaly_detection",
      "workforce_analytics",
      "correlation_analysis",
    ],
    supportedExecutionSteps: [
      "prepare_metric",
      "prepare_dimension",
      "prepare_date_field",
      "aggregate",
      "compare",
      "forecast",
      "correlate",
      "detect_anomaly",
      "summarize",
    ],
    supportedResultTypes: ["table", "summary", "diagnostic", "explanation", "chart_preview"],
    supportsWorkbookRelationships: false,
    supportsForecasting: true,
    supportsCorrelation: true,
    supportsAnomalyDetection: true,
    supportsStatisticalAnalysis: true,
    supportsVisualization: true,
    readinessLevel: "metadata_only",
  },
];

export const listEngineAdapters = () => engineAdapterRegistry;

export const getEngineAdapterById = (engineId: EngineAdapter["id"]) =>
  engineAdapterRegistry.find((engine) => engine.id === engineId) || null;
