import type { SqlConcept, SqlConceptId } from "../types";

export const sqlConceptRegistry: Record<SqlConceptId, SqlConcept> = {
  "inner-join": {
    id: "inner-join",
    title: "INNER JOIN",
    category: "join",
    summary: "Returns only rows where both joined tables have matching values.",
    beginnerNote: "Use this when you only want records that exist in both places.",
    advancedNote: "Join predicates should be explicit and checked for duplicate row multiplication.",
    examples: ["SELECT * FROM orders INNER JOIN customers ON orders.customer_id = customers.id;"],
    relatedConceptIds: ["left-outer-join", "where"],
  },
  "left-outer-join": {
    id: "left-outer-join",
    title: "LEFT OUTER JOIN",
    category: "join",
    summary: "Returns every row from the left table plus matching rows from the right table.",
    beginnerNote: "Use this when the first table is your main list and matches are optional.",
    advancedNote: "Filters on right-table columns can accidentally turn a left join into inner-join behavior.",
    examples: ["SELECT * FROM customers LEFT OUTER JOIN orders ON customers.id = orders.customer_id;"],
    relatedConceptIds: ["inner-join", "where"],
  },
  "right-outer-join": {
    id: "right-outer-join",
    title: "RIGHT OUTER JOIN",
    category: "join",
    summary: "Returns every row from the right table plus matching rows from the left table.",
    beginnerNote: "This is like a left join with the table order reversed.",
    advancedNote: "A translator may prefer rewriting this as a left join to keep generated SQL simpler.",
    examples: ["SELECT * FROM orders RIGHT OUTER JOIN customers ON orders.customer_id = customers.id;"],
    relatedConceptIds: ["left-outer-join", "full-outer-join"],
  },
  "full-outer-join": {
    id: "full-outer-join",
    title: "FULL OUTER JOIN",
    category: "join",
    summary: "Returns matched and unmatched rows from both joined tables.",
    beginnerNote: "Use this to compare two lists while keeping items missing from either side.",
    advancedNote: "Dialect support varies; MariaDB-style SQL needs a warning or future rewrite strategy.",
    examples: ["SELECT * FROM expected FULL OUTER JOIN actual ON expected.id = actual.id;"],
    relatedConceptIds: ["left-outer-join", "right-outer-join"],
  },
  where: {
    id: "where",
    title: "WHERE",
    category: "filter",
    summary: "Filters rows before grouping or aggregation happens.",
    beginnerNote: "Use WHERE to keep only rows that match a condition.",
    advancedNote: "Conditions on raw rows belong in WHERE; aggregate conditions belong in HAVING.",
    examples: ["SELECT * FROM data WHERE status = 'Active';"],
    relatedConceptIds: ["having", "group-by"],
  },
  "group-by": {
    id: "group-by",
    title: "GROUP BY",
    category: "grouping",
    summary: "Combines rows into groups so aggregate functions can summarize each group.",
    beginnerNote: "Use this for questions like totals by category or averages by month.",
    advancedNote: "Selected non-aggregate expressions must be grouped or functionally dependent by dialect rules.",
    examples: ["SELECT category, COUNT(*) AS row_count FROM data GROUP BY category;"],
    relatedConceptIds: ["aggregate-functions", "having", "order-by"],
  },
  having: {
    id: "having",
    title: "HAVING",
    category: "filter",
    summary: "Filters grouped results after aggregate functions are calculated.",
    beginnerNote: "Use HAVING when you want to filter totals, counts, averages, or other summaries.",
    advancedNote: "HAVING can reference aggregate expressions; WHERE generally cannot.",
    examples: ["SELECT category, COUNT(*) AS row_count FROM data GROUP BY category HAVING COUNT(*) > 10;"],
    relatedConceptIds: ["group-by", "aggregate-functions"],
  },
  "order-by": {
    id: "order-by",
    title: "ORDER BY",
    category: "sorting",
    summary: "Sorts the returned rows by one or more columns or expressions.",
    beginnerNote: "Use this to put biggest, smallest, newest, or oldest values first.",
    advancedNote: "Ordering by aliases is common, but exact alias rules vary by dialect and query shape.",
    examples: ["SELECT category, COUNT(*) AS row_count FROM data GROUP BY category ORDER BY row_count DESC;"],
    relatedConceptIds: ["aliases", "aggregate-functions"],
  },
  "case-when": {
    id: "case-when",
    title: "CASE WHEN",
    category: "expression",
    summary: "Creates conditional values inside a SQL query.",
    beginnerNote: "Use this to label rows, bucket values, or create yes/no fields.",
    advancedNote: "CASE result types should be compatible across branches to avoid implicit casts.",
    examples: ["SELECT CASE WHEN amount >= 100 THEN 'High' ELSE 'Standard' END AS amount_band FROM data;"],
    relatedConceptIds: ["aliases", "nested-functions"],
  },
  aliases: {
    id: "aliases",
    title: "Aliases",
    category: "expression",
    summary: "Gives a column, expression, or table a temporary name inside a query.",
    beginnerNote: "Use aliases to make result columns easier to read.",
    advancedNote: "Alias visibility differs between SELECT, WHERE, GROUP BY, HAVING, and ORDER BY by dialect.",
    examples: ["SELECT COUNT(*) AS row_count FROM data;"],
    relatedConceptIds: ["aggregate-functions", "order-by"],
  },
  "aggregate-functions": {
    id: "aggregate-functions",
    title: "Aggregate Functions",
    category: "function",
    summary: "Summarize multiple rows into one value, such as COUNT, SUM, AVG, MIN, or MAX.",
    beginnerNote: "Use aggregates when the question asks for totals, counts, averages, or extremes.",
    advancedNote: "Aggregates interact with GROUP BY, HAVING, null handling, and distinct values.",
    examples: ["SELECT region, AVG(amount) AS avg_amount FROM data GROUP BY region;"],
    relatedConceptIds: ["group-by", "having", "aliases"],
  },
  "single-row-functions": {
    id: "single-row-functions",
    title: "Single-Row Functions",
    category: "function",
    summary: "Transform one row value at a time, such as LENGTH, ROUND, REPLACE, or TO_CHAR.",
    beginnerNote: "Use these to clean, format, or calculate values for each row.",
    advancedNote: "Function names and date formatting tokens are common dialect differences.",
    examples: ["SELECT REPLACE(name, 'Inc.', '') AS clean_name FROM data;"],
    relatedConceptIds: ["nested-functions", "aliases"],
  },
  "nested-functions": {
    id: "nested-functions",
    title: "Nested Functions",
    category: "function",
    summary: "Uses one function call inside another function call.",
    beginnerNote: "SQL evaluates the inside function first, then passes that result outward.",
    advancedNote: "Nested expressions can change types; validators should track the output type when possible.",
    examples: ["SELECT LENGTH(REPLACE(phone, '-', '')) AS digit_count FROM data;"],
    relatedConceptIds: ["single-row-functions", "case-when"],
  },
};

export const getSqlConcept = (conceptId: SqlConceptId): SqlConcept =>
  sqlConceptRegistry[conceptId];

export const listSqlConcepts = (): SqlConcept[] => Object.values(sqlConceptRegistry);
