import type { SqlValidationRule } from "./sqlValidationTypes";

export const selectOnlySafetyRules: SqlValidationRule[] = [
  {
    ruleId: "safety-insert",
    category: "safety",
    severity: "error",
    pattern: /\bINSERT\b/gi,
    message: "INSERT changes data and is outside FiltraQueri's read-only SQL safety model.",
    suggestedAction: "Use a SELECT query for analysis.",
  },
  {
    ruleId: "safety-update",
    category: "safety",
    severity: "error",
    pattern: /\bUPDATE\b/gi,
    message: "UPDATE changes data and should not run from the analytics workspace.",
    suggestedAction: "Use SELECT with calculated columns instead of modifying data.",
  },
  {
    ruleId: "safety-delete",
    category: "safety",
    severity: "error",
    pattern: /\bDELETE\b/gi,
    message: "DELETE removes data and is outside read-only analytics.",
    suggestedAction: "Use WHERE to filter rows without deleting them.",
  },
  {
    ruleId: "safety-drop",
    category: "safety",
    severity: "error",
    pattern: /\bDROP\b/gi,
    message: "DROP removes database objects and is not safe for this workspace.",
    suggestedAction: "Use SELECT statements only.",
  },
  {
    ruleId: "safety-alter",
    category: "safety",
    severity: "error",
    pattern: /\bALTER\b/gi,
    message: "ALTER changes database structure and is not part of read-only analysis.",
    suggestedAction: "Keep the query read-only.",
  },
  {
    ruleId: "safety-truncate-statement",
    category: "safety",
    severity: "error",
    pattern: /\bTRUNCATE\s+(?:TABLE\s+)?[A-Za-z_"][A-Za-z0-9_"]*/gi,
    message: "TRUNCATE as a statement removes table rows.",
    suggestedAction: "Use SELECT with filters instead of destructive table operations.",
  },
  {
    ruleId: "safety-create",
    category: "safety",
    severity: "error",
    pattern: /\bCREATE\b/gi,
    message: "CREATE changes database structure and is not part of read-only analysis.",
    suggestedAction: "Use a SELECT query against the active dataset.",
  },
  {
    ruleId: "safety-replace-table",
    category: "safety",
    severity: "error",
    pattern: /\bREPLACE\s+TABLE\b/gi,
    message: "REPLACE TABLE can overwrite database objects.",
    suggestedAction: "Avoid table mutation in the SQL workspace.",
  },
  {
    ruleId: "safety-copy-to",
    category: "safety",
    severity: "error",
    pattern: /\bCOPY\b[\s\S]*\bTO\b/gi,
    message: "COPY TO performs export-style database operations outside the current result/export flow.",
    suggestedAction: "Use FiltraQueri Export CSV for active results.",
  },
  {
    ruleId: "safety-export",
    category: "safety",
    severity: "error",
    pattern: /\bEXPORT\b/gi,
    message: "EXPORT is outside the read-only SQL workspace safety model.",
    suggestedAction: "Use the app's Export CSV action for active results.",
  },
  {
    ruleId: "safety-attach",
    category: "safety",
    severity: "error",
    pattern: /\bATTACH\b/gi,
    message: "ATTACH can connect external database files and is not allowed in this workspace model.",
    suggestedAction: "Query the active uploaded dataset only.",
  },
];

export const clausePresenceRules: SqlValidationRule[] = [
  {
    ruleId: "clause-select",
    category: "clause",
    severity: "info",
    pattern: /\bSELECT\b/gi,
    message: "SELECT chooses the columns or expressions returned by the query.",
    suggestedAction: "Keep SELECT focused on the columns or calculations you need.",
    concept: "aliases",
  },
  {
    ruleId: "clause-from",
    category: "clause",
    severity: "info",
    pattern: /\bFROM\b/gi,
    message: "FROM identifies the table or subquery being read.",
    suggestedAction: "Use the active dataset table unless a future multi-dataset workflow is enabled.",
  },
  {
    ruleId: "clause-where",
    category: "clause",
    severity: "info",
    pattern: /\bWHERE\b/gi,
    message: "WHERE filters rows before grouping or aggregation.",
    suggestedAction: "Use HAVING instead when filtering aggregate results.",
    concept: "where",
  },
  {
    ruleId: "clause-group-by",
    category: "clause",
    severity: "info",
    pattern: /\bGROUP\s+BY\b/gi,
    message: "GROUP BY combines rows so aggregate functions can summarize each group.",
    suggestedAction: "Include non-aggregate selected columns in the grouping list.",
    concept: "group-by",
  },
  {
    ruleId: "clause-having",
    category: "clause",
    severity: "info",
    pattern: /\bHAVING\b/gi,
    message: "HAVING filters grouped aggregate results.",
    suggestedAction: "Use WHERE for raw row filters and HAVING for aggregate filters.",
    concept: "having",
  },
  {
    ruleId: "clause-order-by",
    category: "clause",
    severity: "info",
    pattern: /\bORDER\s+BY\b/gi,
    message: "ORDER BY sorts the result rows.",
    suggestedAction: "Sort by a selected column, expression, or compatible alias.",
    concept: "order-by",
  },
  {
    ruleId: "clause-limit",
    category: "clause",
    severity: "info",
    pattern: /\bLIMIT\s+\d+\b/gi,
    message: "LIMIT caps the number of returned rows.",
    suggestedAction: "Use LIMIT for smaller previews while exploring data.",
  },
  {
    ruleId: "clause-fetch-first",
    category: "dialect",
    severity: "info",
    pattern: /\bFETCH\s+FIRST\s+\d+\s+ROWS?\s+ONLY\b/gi,
    message: "FETCH FIRST is common in Oracle-style SQL.",
    suggestedAction: "Future translation can adapt this into DuckDB-compatible row limiting.",
  },
];
