import { taskInputPresets, type AnalyticsTaskInput } from "./taskInputs";
import type { AnalyticsTask } from "./taskTypes";

const dimensionInput: AnalyticsTaskInput = {
  id: "dimension",
  type: "dimension",
  label: "Dimension",
  description: "Optional segment or category used to break down the answer.",
  required: false,
  placeholder: "Choose a segment",
  exampleValues: ["region", "category", "sales_rep"],
};

const thresholdInput: AnalyticsTaskInput = {
  id: "threshold",
  type: "threshold",
  label: "Threshold",
  description: "Business cutoff used to flag records or groups.",
  required: false,
  placeholder: "Choose or enter a threshold",
  exampleValues: ["30 days", "10%", "10000"],
};

export const analyticsTaskRegistry: AnalyticsTask[] = [
  {
    id: "task_best_performing_products",
    label: "Best-Performing Products",
    description: "Rank products or services by a selected business metric.",
    category: "sales_analysis",
    iconKey: "sales",
    beginnerFriendly: true,
    supportedIntents: ["best_performing_products"],
    requiredInputs: [taskInputPresets.entityField, taskInputPresets.metric],
    optionalInputs: [taskInputPresets.dateField, dimensionInput],
    supportedResultTypes: ["table", "summary", "chart_preview", "explanation"],
    supportedEngines: ["duckdb_sql", "excel_workbook", "python_preview"],
    explanationTemplateKey: "explain_ranked_business_performance",
    safetyLevel: "metadata_only",
  },
  {
    id: "task_revenue_trend_analysis",
    label: "Revenue Trend Analysis",
    description: "Review how revenue or another metric changes across time.",
    category: "sales_analysis",
    iconKey: "trend",
    beginnerFriendly: true,
    supportedIntents: ["revenue_trend_analysis"],
    requiredInputs: [taskInputPresets.metric, taskInputPresets.dateField],
    optionalInputs: [taskInputPresets.groupingField],
    supportedResultTypes: ["table", "summary", "chart_preview", "explanation"],
    supportedEngines: ["duckdb_sql", "excel_workbook", "python_preview", "r_preview"],
    explanationTemplateKey: "explain_time_series_trend",
    safetyLevel: "metadata_only",
  },
  {
    id: "task_compare_departments",
    label: "Compare Departments",
    description: "Compare teams, departments, or business units by a selected metric.",
    category: "workforce_analytics",
    iconKey: "compare",
    beginnerFriendly: true,
    supportedIntents: ["compare_departments"],
    requiredInputs: [taskInputPresets.groupingField, taskInputPresets.metric],
    optionalInputs: [taskInputPresets.dateField],
    supportedResultTypes: ["table", "summary", "chart_preview", "explanation"],
    supportedEngines: ["duckdb_sql", "excel_workbook", "python_preview", "r_preview"],
    explanationTemplateKey: "explain_segment_comparison",
    safetyLevel: "metadata_only",
  },
  {
    id: "task_forecast_revenue",
    label: "Forecast Revenue",
    description: "Prepare a future-looking revenue forecast workflow from historical data.",
    category: "forecasting",
    iconKey: "forecast",
    beginnerFriendly: true,
    supportedIntents: ["forecast_revenue"],
    requiredInputs: [taskInputPresets.metric, taskInputPresets.dateField],
    optionalInputs: [
      {
        id: "time-range",
        type: "timeRange",
        label: "Forecast period",
        description: "Future period the user wants to forecast.",
        required: false,
        placeholder: "Choose a forecast horizon",
        exampleValues: ["next month", "next quarter", "next 12 weeks"],
      },
    ],
    supportedResultTypes: ["table", "summary", "chart_preview", "explanation"],
    supportedEngines: ["python_preview", "r_preview", "duckdb_sql"],
    explanationTemplateKey: "explain_forecast_preview",
    safetyLevel: "metadata_only",
  },
  {
    id: "task_customer_inactivity_detection",
    label: "Customer Inactivity Detection",
    description: "Identify customers or accounts that have not been active recently.",
    category: "customer_analytics",
    iconKey: "customer",
    beginnerFriendly: true,
    supportedIntents: ["customer_inactivity_check"],
    requiredInputs: [taskInputPresets.entityField, taskInputPresets.dateField],
    optionalInputs: [thresholdInput],
    supportedResultTypes: ["table", "summary", "diagnostic", "explanation"],
    supportedEngines: ["duckdb_sql", "excel_workbook", "python_preview"],
    explanationTemplateKey: "explain_inactive_entities",
    safetyLevel: "metadata_only",
  },
  {
    id: "task_correlation_analysis",
    label: "Correlation Analysis",
    description: "Check whether two business measures appear to move together.",
    category: "correlation_analysis",
    iconKey: "correlation",
    beginnerFriendly: false,
    supportedIntents: ["correlation_check"],
    requiredInputs: [
      {
        id: "first-metric",
        type: "metric",
        label: "First metric",
        description: "First numeric measure.",
        required: true,
        placeholder: "Choose the first metric",
        exampleValues: ["discount", "cost", "quantity"],
      },
      {
        id: "second-metric",
        type: "metric",
        label: "Second metric",
        description: "Second numeric measure.",
        required: true,
        placeholder: "Choose the second metric",
        exampleValues: ["revenue", "profit", "sales"],
      },
    ],
    optionalInputs: [
      {
        id: "filter-condition",
        type: "filterCondition",
        label: "Filter condition",
        description: "Optional subset of records to inspect.",
        required: false,
        placeholder: "Optionally narrow the analysis",
        exampleValues: ["region is East", "date is this year"],
      },
    ],
    supportedResultTypes: ["table", "summary", "diagnostic", "explanation"],
    supportedEngines: ["python_preview", "r_preview", "duckdb_sql"],
    explanationTemplateKey: "explain_correlation_check",
    safetyLevel: "metadata_only",
  },
  {
    id: "task_unusual_sales_behavior",
    label: "Unusual Sales Behavior",
    description: "Detect unusually high, low, or inconsistent sales patterns.",
    category: "anomaly_detection",
    iconKey: "anomaly",
    beginnerFriendly: true,
    supportedIntents: ["unusual_sales_behavior"],
    requiredInputs: [taskInputPresets.metric],
    optionalInputs: [taskInputPresets.dateField, dimensionInput, thresholdInput],
    supportedResultTypes: ["table", "summary", "diagnostic", "explanation"],
    supportedEngines: ["duckdb_sql", "excel_workbook", "python_preview", "r_preview"],
    explanationTemplateKey: "explain_anomaly_candidates",
    safetyLevel: "metadata_only",
  },
  {
    id: "task_profit_drop_investigation",
    label: "Profit Drop Investigation",
    description: "Investigate where profit decreased and which groups may be contributing.",
    category: "financial_analysis",
    iconKey: "financial",
    beginnerFriendly: true,
    supportedIntents: ["profit_drop_investigation"],
    requiredInputs: [taskInputPresets.metric, taskInputPresets.dateField],
    optionalInputs: [taskInputPresets.groupingField, dimensionInput],
    supportedResultTypes: ["table", "summary", "diagnostic", "explanation"],
    supportedEngines: ["duckdb_sql", "excel_workbook", "python_preview", "r_preview"],
    explanationTemplateKey: "explain_profit_drop_investigation",
    safetyLevel: "metadata_only",
  },
];

export const listAnalyticsTasks = () => analyticsTaskRegistry;

export const getAnalyticsTaskById = (taskId: string) =>
  analyticsTaskRegistry.find((task) => task.id === taskId) || null;

export const listAnalyticsTasksByIntent = (intentId: string) =>
  analyticsTaskRegistry.filter((task) => task.supportedIntents.includes(intentId));

export const listAnalyticsTasksByCategory = (category: AnalyticsTask["category"]) =>
  analyticsTaskRegistry.filter((task) => task.category === category);
