import type { SchemaColumn } from "../../dataset/datasetTypes";
import type { SqlDialectId } from "../../sqlIntelligence";
import type {
  AcceptedRelationshipContract,
  AnalysisScopeSelection,
  WorksheetMetadata,
} from "../../workbook";
import {
  createEmptyBusinessSqlQueryPlan,
  type BusinessSqlJoinEdge,
  type BusinessSqlJoinRequirement,
  type BusinessSqlPlanSupportLevel,
  type BusinessSqlQueryPlan,
} from "./businessSqlQueryPlan";
import {
  resolveBusinessSqlJoinPath,
  type BusinessSqlMissingRelationship,
} from "./businessSqlJoinPathResolver";

export type PlanBusinessSqlQueryRequestInput = {
  prompt: string;
  selectedGuidanceDialect?: SqlDialectId;
  selectedScopeSelections?: readonly AnalysisScopeSelection[];
  appliedScopeSelections?: readonly AnalysisScopeSelection[];
  worksheets?: readonly Pick<WorksheetMetadata, "tableName" | "schema">[];
  entities?: readonly BusinessSqlAvailableEntityMetadata[];
  acceptedRelationshipContracts?: readonly AcceptedRelationshipContract[];
  readyRelationshipContracts?: readonly AcceptedRelationshipContract[];
  missingRelationships?: readonly BusinessSqlMissingRelationship[];
};

export type BusinessSqlAvailableEntityMetadata = {
  entity: string;
  table?: string;
  columns?: readonly Pick<SchemaColumn, "name">[];
};

type PlannerPattern =
  | "leased_units_per_property"
  | "leases_by_status"
  | "orders_per_customer"
  | "tickets_per_account";

const normalizePrompt = (prompt: string): string =>
  prompt
    .toLowerCase()
    .replace(/['']/g, "'")
    .replace(/[^a-z0-9_]+/g, " ")
    .replace(/\s+/g, " ")
    .trim();

const sameName = (left: string | undefined, right: string | undefined): boolean =>
  Boolean(left && right && left.trim().toLowerCase() === right.trim().toLowerCase());

const tableForEntity = (
  entity: string,
  input: PlanBusinessSqlQueryRequestInput,
): string => {
  const directEntity = input.entities?.find((candidate) =>
    sameName(candidate.entity, entity),
  );
  if (directEntity?.table) return directEntity.table;

  const scopeTable = [
    ...(input.appliedScopeSelections || []),
    ...(input.selectedScopeSelections || []),
  ].find((selection) => sameName(selection.tableName, entity));
  if (scopeTable?.tableName) return scopeTable.tableName;

  const worksheet = input.worksheets?.find((candidate) =>
    sameName(candidate.tableName, entity),
  );
  return worksheet?.tableName || entity;
};

const rendererFor = (
  selectedGuidanceDialect: SqlDialectId | undefined,
  support: BusinessSqlPlanSupportLevel,
): BusinessSqlQueryPlan["renderer"] => ({
  targetDialect: "duckdb",
  selectedGuidanceDialect,
  status: support === "blocked" ? "blocked" : "not_rendered",
  notes: [
    "Uploaded datasets execute against DuckDB by default.",
    ...(selectedGuidanceDialect
      ? [`${selectedGuidanceDialect} is recorded only as guidance metadata.`]
      : []),
    "No SQL has been generated by the deterministic planner.",
  ],
});

const joinRequirement = (
  fromEntity: string,
  toEntity: string,
  relationship: string,
): BusinessSqlJoinRequirement => ({
  fromEntity,
  toEntity,
  required: true,
  relationship,
  verified: false,
});

const joinEdge = (
  fromEntity: string,
  fromTable: string,
  fromField: string,
  toEntity: string,
  toTable: string,
  toField: string,
  relationship: string,
): BusinessSqlJoinEdge => ({
  fromEntity,
  fromTable,
  fromField,
  toEntity,
  toTable,
  toField,
  relationship,
  verified: false,
});

const unsupportedPlan = (
  prompt: string,
  selectedGuidanceDialect: SqlDialectId | undefined,
): BusinessSqlQueryPlan => ({
  ...createEmptyBusinessSqlQueryPlan(),
  id: "business-sql-plan:needs-review",
  kind: "empty",
  status: "draft",
  support: "needs_review",
  prompt,
  warnings: [
    {
      id: "unsupported-business-request",
      severity: "warning",
      message:
        "This business request is not specific enough for deterministic planning yet.",
    },
  ],
  renderer: rendererFor(selectedGuidanceDialect, "needs_review"),
  preview: {
    title: "Needs review business SQL query plan",
    metricSummary: "No deterministic metric was selected.",
    groupingSummary: "No deterministic grouping was selected.",
    filterSummary: "No deterministic filters were selected.",
    joinSummary: "No join path was resolved.",
    rendererSummary: "SQL has not been rendered.",
  },
});

const leasesByStatusPlan = (
  prompt: string,
  selectedGuidanceDialect: SqlDialectId | undefined,
): BusinessSqlQueryPlan => ({
  ...createEmptyBusinessSqlQueryPlan(),
  id: "business-sql-plan:leases-by-status",
  kind: "single_table_count_grouping",
  status: "resolved",
  support: "supported",
  prompt,
  entities: [{ entity: "leases", table: "leases", required: true, role: "source" }],
  metric: {
    kind: "count_entities",
    entity: "leases",
    table: "leases",
    distinct: false,
    label: "count leases",
  },
  groupings: [
    {
      entity: "leases",
      table: "leases",
      field: "lease_status",
      label: "lease_status",
    },
  ],
  renderer: rendererFor(selectedGuidanceDialect, "supported"),
  preview: {
    title: "Leases by status",
    metricSummary: "Count lease records.",
    groupingSummary: "Grouped by lease_status.",
    filterSummary: "No active/current filter is implied.",
    joinSummary: "No join path required.",
    rendererSummary: "SQL has not been rendered.",
  },
});

const ordersPerCustomerPlan = (
  prompt: string,
  selectedGuidanceDialect: SqlDialectId | undefined,
): BusinessSqlQueryPlan => ({
  ...createEmptyBusinessSqlQueryPlan(),
  id: "business-sql-plan:orders-per-customer",
  kind: "multi_table_count_grouping",
  status: "resolved",
  support: "needs_review",
  prompt,
  entities: [
    { entity: "customers", table: "customers", required: true, role: "grouping_subject" },
    { entity: "orders", table: "orders", required: true, role: "metric_subject" },
  ],
  metric: {
    kind: "count_entities",
    entity: "orders",
    table: "orders",
    distinct: false,
    label: "count orders",
  },
  groupings: [
    { entity: "customers", table: "customers", field: "customer_id", label: "customer" },
  ],
  joinPath: {
    required: true,
    status: "needs_review",
    entities: ["customers", "orders"],
    requirements: [joinRequirement("customers", "orders", "customer has orders")],
    edges: [
      joinEdge(
        "customers",
        "customers",
        "customer_id",
        "orders",
        "orders",
        "customer_id",
        "customer has orders",
      ),
    ],
  },
  warnings: [
    {
      id: "join-path-needs-review",
      severity: "warning",
      message: "Join path customers → orders must be verified before SQL rendering.",
    },
  ],
  renderer: rendererFor(selectedGuidanceDialect, "needs_review"),
  preview: {
    title: "Orders per customer",
    metricSummary: "Count order records.",
    groupingSummary: "Grouped by customer.",
    filterSummary: "No filters selected.",
    joinSummary: "Requires customers -> orders.",
    rendererSummary: "SQL has not been rendered.",
  },
});

const ticketsPerAccountPlan = (
  prompt: string,
  selectedGuidanceDialect: SqlDialectId | undefined,
): BusinessSqlQueryPlan => ({
  ...createEmptyBusinessSqlQueryPlan(),
  id: "business-sql-plan:tickets-per-account",
  kind: "multi_table_count_grouping",
  status: "resolved",
  support: "needs_review",
  prompt,
  entities: [
    { entity: "accounts", table: "accounts", required: true, role: "grouping_subject" },
    { entity: "tickets", table: "tickets", required: true, role: "metric_subject" },
  ],
  metric: {
    kind: "count_entities",
    entity: "tickets",
    table: "tickets",
    distinct: false,
    label: "count tickets",
  },
  groupings: [
    { entity: "accounts", table: "accounts", field: "account_id", label: "account" },
  ],
  joinPath: {
    required: true,
    status: "needs_review",
    entities: ["accounts", "tickets"],
    requirements: [joinRequirement("accounts", "tickets", "account has tickets")],
    edges: [
      joinEdge(
        "accounts",
        "accounts",
        "account_id",
        "tickets",
        "tickets",
        "account_id",
        "account has tickets",
      ),
    ],
  },
  warnings: [
    {
      id: "join-path-needs-review",
      severity: "warning",
      message: "Join path accounts → tickets must be verified before SQL rendering.",
    },
  ],
  renderer: rendererFor(selectedGuidanceDialect, "needs_review"),
  preview: {
    title: "Tickets per account",
    metricSummary: "Count ticket records.",
    groupingSummary: "Grouped by account.",
    filterSummary: "No filters selected.",
    joinSummary: "Requires accounts -> tickets.",
    rendererSummary: "SQL has not been rendered.",
  },
});

const leasedUnitsPerPropertyPlan = (
  prompt: string,
  selectedGuidanceDialect: SqlDialectId | undefined,
): BusinessSqlQueryPlan => ({
  ...createEmptyBusinessSqlQueryPlan(),
  id: "business-sql-plan:leased-units-per-property",
  kind: "multi_table_count_grouping",
  status: "resolved",
  support: "needs_review",
  prompt,
  entities: [
    { entity: "properties", table: "properties", required: true, role: "grouping_subject" },
    { entity: "units", table: "units", field: "unit_id", required: true, role: "metric_subject" },
    { entity: "leases", table: "leases", required: true, role: "filter_subject" },
    { entity: "tenants", table: "tenants", required: false, role: "context" },
  ],
  metric: {
    kind: "count_distinct",
    entity: "units",
    table: "units",
    field: "unit_id",
    distinct: true,
    label: "count distinct units",
  },
  groupings: [
    {
      entity: "properties",
      table: "properties",
      field: "property_id",
      label: "property",
    },
  ],
  filters: [
    {
      kind: "relationship_predicate",
      entity: "leases",
      table: "leases",
      predicate: "active_current_lease or leased_to_tenants",
      label: "leased to current tenants",
    },
  ],
  joinPath: {
    required: true,
    status: "needs_review",
    entities: ["properties", "units", "leases"],
    requirements: [
      joinRequirement("properties", "units", "property has units"),
      joinRequirement("units", "leases", "unit has leases"),
    ],
    edges: [
      joinEdge(
        "properties",
        "properties",
        "property_id",
        "units",
        "units",
        "property_id",
        "property has units",
      ),
      joinEdge(
        "units",
        "units",
        "unit_id",
        "leases",
        "leases",
        "unit_id",
        "unit has leases",
      ),
    ],
  },
  assumptions: [
    {
      id: "current-lease-semantics",
      label: "Current lease semantics",
      detail: "A current tenant means an active lease or a lease date range containing today.",
    },
  ],
  warnings: [
    {
      id: "join-path-needs-review",
      severity: "warning",
      message: "Join path properties → units → leases must be verified before SQL rendering.",
    },
  ],
  renderer: rendererFor(selectedGuidanceDialect, "needs_review"),
  preview: {
    title: "Leased units per property",
    metricSummary: "Count distinct units, not leases.",
    groupingSummary: "Grouped by property.",
    filterSummary: "Only active/current leased-to-tenant semantics qualify.",
    joinSummary: "Requires properties -> units -> leases.",
    rendererSummary: "SQL has not been rendered.",
  },
});

const detectPattern = (prompt: string): PlannerPattern | null => {
  const text = normalizePrompt(prompt);
  if (!text) return null;

  const leasesByStatus =
    /\b(count|counts|many|number)\b.*\bleases?\b.*\b(status|statuses)\b/.test(text) ||
    /\blease status counts?\b/.test(text) ||
    /\bleases?\b.*\b(each|by|per)\b.*\bstatus\b/.test(text);
  if (leasesByStatus) return "leases_by_status";

  const leasedUnitsPerProperty =
    /\bleased units?\b.*\b(by|per|each)\b.*\bpropert/.test(text) ||
    /\b(count|counts|many|number)\b.*\bleased units?\b.*\bpropert/.test(text) ||
    (/\bunits?\b.*\b(each|by|per|in)\b.*\bpropert/.test(text) &&
      /\b(leased|current tenants?|tenants?)\b/.test(text)) ||
    (/\bcurrent tenants?\b.*\bpropert/.test(text) && /\bunits?\b/.test(text));
  if (leasedUnitsPerProperty) return "leased_units_per_property";

  const ordersPerCustomer =
    /\borders?\b.*\b(per|by|each)\b.*\bcustomers?\b/.test(text) ||
    /\b(count|counts|many|number)\b.*\borders?\b.*\bcustomers?\b/.test(text) ||
    /\bhow many orders?\b.*\beach customers?\b/.test(text);
  if (ordersPerCustomer) return "orders_per_customer";

  const ticketsPerAccount =
    /\btickets?\b.*\b(per|by|for each|each)\b.*\baccounts?\b/.test(text) ||
    /\b(count|counts|many|number)\b.*\btickets?\b.*\baccounts?\b/.test(text) ||
    /\bhow many tickets?\b.*\beach accounts?\b/.test(text);
  if (ticketsPerAccount) return "tickets_per_account";

  return null;
};

const selectInitialPlan = (
  prompt: string,
  selectedGuidanceDialect: SqlDialectId | undefined,
): BusinessSqlQueryPlan => {
  const pattern = detectPattern(prompt);

  switch (pattern) {
    case "leased_units_per_property":
      return leasedUnitsPerPropertyPlan(prompt, selectedGuidanceDialect);
    case "leases_by_status":
      return leasesByStatusPlan(prompt, selectedGuidanceDialect);
    case "orders_per_customer":
      return ordersPerCustomerPlan(prompt, selectedGuidanceDialect);
    case "tickets_per_account":
      return ticketsPerAccountPlan(prompt, selectedGuidanceDialect);
    default:
      return unsupportedPlan(prompt, selectedGuidanceDialect);
  }
};

const resolvePlanTables = (
  plan: BusinessSqlQueryPlan,
  input: PlanBusinessSqlQueryRequestInput,
): BusinessSqlQueryPlan => {
  const entities = plan.entities.map((entity) => ({
    ...entity,
    table: tableForEntity(entity.entity, input),
  }));

  return {
    ...plan,
    entities,
    metric: plan.metric
      ? {
          ...plan.metric,
          table: plan.metric.entity
            ? tableForEntity(plan.metric.entity, input)
            : plan.metric.table,
        }
      : plan.metric,
    groupings: plan.groupings.map((grouping) => ({
      ...grouping,
      table: tableForEntity(grouping.entity, input),
    })),
    filters: plan.filters.map((filter) => ({
      ...filter,
      table: filter.entity ? tableForEntity(filter.entity, input) : filter.table,
    })),
    joinPath: {
      ...plan.joinPath,
      edges: plan.joinPath.edges.map((edge) => ({
        ...edge,
        fromTable: tableForEntity(edge.fromEntity, input),
        toTable: tableForEntity(edge.toEntity, input),
      })),
    },
  };
};

export function planBusinessSqlQueryRequest(
  input: PlanBusinessSqlQueryRequestInput,
): BusinessSqlQueryPlan {
  const initialPlan = resolvePlanTables(
    selectInitialPlan(input.prompt, input.selectedGuidanceDialect),
    input,
  );

  if (!initialPlan.joinPath.required) {
    return initialPlan;
  }

  return resolveBusinessSqlJoinPath({
    plan: initialPlan,
    acceptedRelationshipContracts: input.acceptedRelationshipContracts,
    readyRelationshipContracts: input.readyRelationshipContracts,
    missingRelationships: input.missingRelationships,
  });
}
