import type { SqlDialectId } from "../../sqlIntelligence";
import type { AcceptedRelationshipContract } from "../../workbook";
import {
  createEmptyBusinessSqlQueryPlan,
  type BusinessSqlJoinEdge,
  type BusinessSqlJoinRequirement,
  type BusinessSqlPlanSupportLevel,
  type BusinessSqlQueryPlan,
} from "./businessSqlQueryPlan";
import {
  resolveBusinessSqlJoinPath,
  type BusinessSqlMissingRelationship,
} from "./businessSqlJoinPathResolver";

export type PlanBusinessSqlQueryRequestInput = {
  prompt: string;
  selectedGuidanceDialect?: SqlDialectId;
  acceptedRelationshipContracts?: readonly AcceptedRelationshipContract[];
  readyRelationshipContracts?: readonly AcceptedRelationshipContract[];
  missingRelationships?: readonly BusinessSqlMissingRelationship[];
};

const normalizePrompt = (prompt: string): string =>
  prompt.toLowerCase().replace(/\s+/g, " ").trim();

const includesAny = (text: string, values: readonly string[]): boolean =>
  values.some((value) => text.includes(value));

const rendererFor = (
  selectedGuidanceDialect: SqlDialectId | undefined,
  support: BusinessSqlPlanSupportLevel,
): BusinessSqlQueryPlan["renderer"] => ({
  targetDialect: "duckdb",
  selectedGuidanceDialect,
  status: support === "blocked" ? "blocked" : "not_rendered",
  notes: [
    "Uploaded datasets execute against DuckDB by default.",
    ...(selectedGuidanceDialect
      ? [`${selectedGuidanceDialect} is recorded only as guidance metadata.`]
      : []),
    "No SQL has been generated by the deterministic planner.",
  ],
});

const joinRequirement = (
  fromEntity: string,
  toEntity: string,
  relationship: string,
): BusinessSqlJoinRequirement => ({
  fromEntity,
  toEntity,
  required: true,
  relationship,
  verified: false,
});

const joinEdge = (
  fromEntity: string,
  fromTable: string,
  fromField: string,
  toEntity: string,
  toTable: string,
  toField: string,
  relationship: string,
): BusinessSqlJoinEdge => ({
  fromEntity,
  fromTable,
  fromField,
  toEntity,
  toTable,
  toField,
  relationship,
  verified: false,
});

const unsupportedPlan = (
  prompt: string,
  selectedGuidanceDialect: SqlDialectId | undefined,
): BusinessSqlQueryPlan => ({
  ...createEmptyBusinessSqlQueryPlan(),
  id: "business-sql-plan:needs-review",
  kind: "empty",
  status: "draft",
  support: "needs_review",
  prompt,
  warnings: [
    {
      id: "unsupported-business-request",
      severity: "warning",
      message:
        "This business request is not specific enough for deterministic planning yet.",
    },
  ],
  renderer: rendererFor(selectedGuidanceDialect, "needs_review"),
  preview: {
    title: "Needs review business SQL query plan",
    metricSummary: "No deterministic metric was selected.",
    groupingSummary: "No deterministic grouping was selected.",
    filterSummary: "No deterministic filters were selected.",
    joinSummary: "No join path was resolved.",
    rendererSummary: "SQL has not been rendered.",
  },
});

const leasesByStatusPlan = (
  prompt: string,
  selectedGuidanceDialect: SqlDialectId | undefined,
): BusinessSqlQueryPlan => ({
  ...createEmptyBusinessSqlQueryPlan(),
  id: "business-sql-plan:leases-by-status",
  kind: "single_table_count_grouping",
  status: "resolved",
  support: "supported",
  prompt,
  entities: [{ entity: "leases", table: "leases", required: true, role: "source" }],
  metric: {
    kind: "count_entities",
    entity: "leases",
    table: "leases",
    distinct: false,
    label: "count leases",
  },
  groupings: [
    {
      entity: "leases",
      table: "leases",
      field: "lease_status",
      label: "lease_status",
    },
  ],
  renderer: rendererFor(selectedGuidanceDialect, "supported"),
  preview: {
    title: "Leases by status",
    metricSummary: "Count lease records.",
    groupingSummary: "Grouped by lease_status.",
    filterSummary: "No active/current filter is implied.",
    joinSummary: "No join path required.",
    rendererSummary: "SQL has not been rendered.",
  },
});

const ordersPerCustomerPlan = (
  prompt: string,
  selectedGuidanceDialect: SqlDialectId | undefined,
): BusinessSqlQueryPlan => ({
  ...createEmptyBusinessSqlQueryPlan(),
  id: "business-sql-plan:orders-per-customer",
  kind: "multi_table_count_grouping",
  status: "resolved",
  support: "needs_review",
  prompt,
  entities: [
    { entity: "customers", table: "customers", required: true, role: "grouping_subject" },
    { entity: "orders", table: "orders", required: true, role: "metric_subject" },
  ],
  metric: {
    kind: "count_entities",
    entity: "orders",
    table: "orders",
    distinct: false,
    label: "count orders",
  },
  groupings: [
    { entity: "customers", table: "customers", field: "customer_id", label: "customer" },
  ],
  joinPath: {
    required: true,
    status: "needs_review",
    entities: ["customers", "orders"],
    requirements: [joinRequirement("customers", "orders", "customer has orders")],
    edges: [
      joinEdge(
        "customers",
        "customers",
        "customer_id",
        "orders",
        "orders",
        "customer_id",
        "customer has orders",
      ),
    ],
  },
  warnings: [
    {
      id: "join-path-needs-review",
      severity: "warning",
      message: "Join path customers → orders must be verified before SQL rendering.",
    },
  ],
  renderer: rendererFor(selectedGuidanceDialect, "needs_review"),
  preview: {
    title: "Orders per customer",
    metricSummary: "Count order records.",
    groupingSummary: "Grouped by customer.",
    filterSummary: "No filters selected.",
    joinSummary: "Requires customers -> orders.",
    rendererSummary: "SQL has not been rendered.",
  },
});

const ticketsPerAccountPlan = (
  prompt: string,
  selectedGuidanceDialect: SqlDialectId | undefined,
): BusinessSqlQueryPlan => ({
  ...createEmptyBusinessSqlQueryPlan(),
  id: "business-sql-plan:tickets-per-account",
  kind: "multi_table_count_grouping",
  status: "resolved",
  support: "needs_review",
  prompt,
  entities: [
    { entity: "accounts", table: "accounts", required: true, role: "grouping_subject" },
    { entity: "tickets", table: "tickets", required: true, role: "metric_subject" },
  ],
  metric: {
    kind: "count_entities",
    entity: "tickets",
    table: "tickets",
    distinct: false,
    label: "count tickets",
  },
  groupings: [
    { entity: "accounts", table: "accounts", field: "account_id", label: "account" },
  ],
  joinPath: {
    required: true,
    status: "needs_review",
    entities: ["accounts", "tickets"],
    requirements: [joinRequirement("accounts", "tickets", "account has tickets")],
    edges: [
      joinEdge(
        "accounts",
        "accounts",
        "account_id",
        "tickets",
        "tickets",
        "account_id",
        "account has tickets",
      ),
    ],
  },
  warnings: [
    {
      id: "join-path-needs-review",
      severity: "warning",
      message: "Join path accounts → tickets must be verified before SQL rendering.",
    },
  ],
  renderer: rendererFor(selectedGuidanceDialect, "needs_review"),
  preview: {
    title: "Tickets per account",
    metricSummary: "Count ticket records.",
    groupingSummary: "Grouped by account.",
    filterSummary: "No filters selected.",
    joinSummary: "Requires accounts -> tickets.",
    rendererSummary: "SQL has not been rendered.",
  },
});

const leasedUnitsPerPropertyPlan = (
  prompt: string,
  selectedGuidanceDialect: SqlDialectId | undefined,
): BusinessSqlQueryPlan => ({
  ...createEmptyBusinessSqlQueryPlan(),
  id: "business-sql-plan:leased-units-per-property",
  kind: "multi_table_count_grouping",
  status: "resolved",
  support: "needs_review",
  prompt,
  entities: [
    { entity: "properties", table: "properties", required: true, role: "grouping_subject" },
    { entity: "units", table: "units", field: "unit_id", required: true, role: "metric_subject" },
    { entity: "leases", table: "leases", required: true, role: "filter_subject" },
    { entity: "tenants", table: "tenants", required: false, role: "context" },
  ],
  metric: {
    kind: "count_distinct",
    entity: "units",
    table: "units",
    field: "unit_id",
    distinct: true,
    label: "count distinct units",
  },
  groupings: [
    {
      entity: "properties",
      table: "properties",
      field: "property_id",
      label: "property",
    },
  ],
  filters: [
    {
      kind: "relationship_predicate",
      entity: "leases",
      table: "leases",
      predicate: "active_current_lease or leased_to_tenants",
      label: "leased to current tenants",
    },
  ],
  joinPath: {
    required: true,
    status: "needs_review",
    entities: ["properties", "units", "leases"],
    requirements: [
      joinRequirement("properties", "units", "property has units"),
      joinRequirement("units", "leases", "unit has leases"),
    ],
    edges: [
      joinEdge(
        "properties",
        "properties",
        "property_id",
        "units",
        "units",
        "property_id",
        "property has units",
      ),
      joinEdge(
        "units",
        "units",
        "unit_id",
        "leases",
        "leases",
        "unit_id",
        "unit has leases",
      ),
    ],
  },
  assumptions: [
    {
      id: "current-lease-semantics",
      label: "Current lease semantics",
      detail: "A current tenant means an active lease or a lease date range containing today.",
    },
  ],
  warnings: [
    {
      id: "join-path-needs-review",
      severity: "warning",
      message: "Join path properties → units → leases must be verified before SQL rendering.",
    },
  ],
  renderer: rendererFor(selectedGuidanceDialect, "needs_review"),
  preview: {
    title: "Leased units per property",
    metricSummary: "Count distinct units, not leases.",
    groupingSummary: "Grouped by property.",
    filterSummary: "Only active/current leased-to-tenant semantics qualify.",
    joinSummary: "Requires properties -> units -> leases.",
    rendererSummary: "SQL has not been rendered.",
  },
});

const selectInitialPlan = (
  prompt: string,
  selectedGuidanceDialect: SqlDialectId | undefined,
): BusinessSqlQueryPlan => {
  const text = normalizePrompt(prompt);

  if (
    includesAny(text, ["leased units per property", "units in each property"]) ||
    (includesAny(text, ["leased", "current tenant"]) &&
      includesAny(text, ["unit", "units"]) &&
      includesAny(text, ["property", "properties"]))
  ) {
    return leasedUnitsPerPropertyPlan(prompt, selectedGuidanceDialect);
  }

  if (
    includesAny(text, ["leases by status", "lease by status"]) ||
    (includesAny(text, ["lease", "leases"]) && includesAny(text, ["status"]))
  ) {
    return leasesByStatusPlan(prompt, selectedGuidanceDialect);
  }

  if (
    includesAny(text, ["orders per customer", "orders by customer"]) ||
    (includesAny(text, ["order", "orders"]) && includesAny(text, ["customer", "customers"]))
  ) {
    return ordersPerCustomerPlan(prompt, selectedGuidanceDialect);
  }

  if (
    includesAny(text, ["tickets per account", "tickets by account"]) ||
    (includesAny(text, ["ticket", "tickets"]) && includesAny(text, ["account", "accounts"]))
  ) {
    return ticketsPerAccountPlan(prompt, selectedGuidanceDialect);
  }

  return unsupportedPlan(prompt, selectedGuidanceDialect);
};

export function planBusinessSqlQueryRequest(
  input: PlanBusinessSqlQueryRequestInput,
): BusinessSqlQueryPlan {
  const initialPlan = selectInitialPlan(
    input.prompt,
    input.selectedGuidanceDialect,
  );

  if (!initialPlan.joinPath.required) {
    return initialPlan;
  }

  return resolveBusinessSqlJoinPath({
    plan: initialPlan,
    acceptedRelationshipContracts: input.acceptedRelationshipContracts,
    readyRelationshipContracts: input.readyRelationshipContracts,
    missingRelationships: input.missingRelationships,
  });
}
